# Read in csv file using base R
sta_meta <- read.csv("./data/portal_stations.csv", stringsAsFactors = F)

# Take a look at the data
str(sta_meta) # structure, like in the env window
head(sta_meta) # first six rows of data
tail(sta_meta) # last six rows of data
nrow(sta_meta) # number of rows
summary(sta_meta) # summary of the variables, including min/max for numericals and NA count for non-text variables. 


# This code was generated by the import dataset wizard in R Studio
library(readxl)
icebreaker_answers <- read_excel("data/icebreaker_answers.xlsx",
                                 sheet = "Sheet1")
View(icebreaker_answers)
